# Generated by Django 4.2.7 on 2023-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalakriti', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image_path',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
